version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: app_redis

  celery:
    container_name: booking_celery
    build:
      context: .
    working_dir: /app
    command: ["celery"]
    depends_on:
      - redis

  main_app:
    build: .
    container_name: main_app
    depends_on:
      - celery