version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis_ai_seo

  celery_chatgpt:
    container_name: celery_chatgpt
    build:
      context: .
    working_dir: /app
    command: ["celery", "-A", "tasks", "worker", "--loglevel=INFO",
              "--pool=prefork", "--concurrency=4", "--queues=chatgpt", "-n", "mpstats@fedora"]
    depends_on:
      - redis

  celery_mpstats:
    container_name: celery_mpstats
    build:
      context: .
    working_dir: /app
    command: ["celery", "-A", "tasks", "worker", "--loglevel=INFO",
              "--pool=prefork", "--concurrency=1", "--queues=mpstats", "-n", "mpstats@fedora" ]
    depends_on:
      - redis

  main_app:
    build: .
    container_name: main_app
    depends_on:
      - celery_mpstats
      - celery_chatgpt
      - redis
