version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: app_redis
    ports:
      - "6379:6379"
  celery:
    container_name: booking_celery
    build:
      context: .
    working_dir: /app
    command: ["celery", "-A", "celery_app", "worker", "--pool=prefork", "--loglevel=INFO"]
    depends_on:
      - redis

  main_app:
    build: .
    container_name: main_app
    depends_on:
      - celery